name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
      - run: yarn size
      - run: yarn prepare
